# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				item = true
				bee = true
				turtle = true
				wolf = true
				villager = true
				donkey = true
				cow = true
				chest_minecart = true
				pig = true
				item_frame = true
				horse = true
				llama = true
				painting = true
				zombie = true
				cave_spider = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				sheep = true
				creeper = true
				lightning_bolt = true
				player = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				super_glue = true

			[light_sources.settings.entities.railways]
				conductor = true

